ai:
  max_concurrent_issues: 3
  max_tokens: 4000
  model: claude-3-sonnet-20240229
  rate_limit_retry: true
daemon:
  max_iterations: 3
  scan_interval: 30
database:
  echo: false
  url: sqlite:///.haunted/haunted.db
git:
  auto_commit: true
  auto_merge: true
  commit_message_template: 'Issue #{issue_id}: {stage} - {description}'
project_root: .
